export const AuditActions = {
  // Auth
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  REGISTER: 'REGISTER',
  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_CONFIRM: 'PASSWORD_RESET_CONFIRM',
  EMAIL_VERIFY: 'EMAIL_VERIFY',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  
  // Users
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  
  // Roles
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  ROLE_ASSIGN: 'ROLE_ASSIGN',
  ROLE_REVOKE: 'ROLE_REVOKE',
  
  // Permissions
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  PERMISSION_DELETE: 'PERMISSION_DELETE',
  
  // Rack
  RACK_CALCULATE: 'RACK_CALCULATE',
  RACK_SAVE: 'RACK_SAVE',
  RACK_UPDATE: 'RACK_UPDATE',
  RACK_DELETE: 'RACK_DELETE',
  
  // Battery
  BATTERY_CALCULATE: 'BATTERY_CALCULATE',
  BATTERY_SAVE: 'BATTERY_SAVE',
  
  // Export
  EXPORT_RACK: 'EXPORT_RACK',
} as const

export type AuditAction = typeof AuditActions[keyof typeof AuditActions]
